name: cupertino_calendar_structre
description: Specific designed data structre which using in Cupertino Calendar
version: 1.0.0-beta-8+1
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  quiver: ^3.0.1
  intl: ^0.17.0
dev_dependencies:
  test: ^1.17.12
