name: cupertino_calendar_structre
description: Specific designed data structre which using in Cupertino Calendar
version: 1.1.2
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
issue_tracker: https://github.com/rk0cc/cupertino_calendar/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  quiver: ^3.2.1
  intl: ^0.18.1
dev_dependencies:
  test: ^1.24.4
