name: cupertino_calendar_structre
description: Specific designed data structre which using in Cupertino Calendar
version: 1.1.1
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
issue_tracker: https://github.com/rk0cc/cupertino_calendar/issues
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  quiver: ^3.0.1+1
  intl: ^0.17.0
dev_dependencies:
  test: ^1.19.1
