name: cupertino_calendar_date_reminds_view
description: Display events and holiday's information in Cupertino Calendar with selectable supported
version: 1.0.3
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
issue_tracker: https://github.com/rk0cc/cupertino_calendar/issues
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar_structre: ^1.1.1
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter