name: cupertino_calendar_date_reminds_view
description: Display events and holiday's information in Cupertino Calendar with selectable supported
version: 1.0.0-rc-2
homepage: https://www.rk0cc.xyz
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar_structre: ^1.0.0-beta-8+1
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter