name: cupertino_calendar
description: A calendar widget special design for Cupertino UI in Flutter
version: 1.0.0-beta-1
homepage: https://www.rk0cc.xyz
environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: