name: cupertino_calendar
description: A calendar widget special design for Cupertino UI in Flutter
version: 1.0.0
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
issue_tracker: https://github.com/rk0cc/cupertino_calendar/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_calendar_structre:
    git:
      url: https://github.com/LahaLuhem/cupertino_calendar
      path: structre/
  cupertino_calendar_month_view:
    git:
      url: https://github.com/LahaLuhem/cupertino_calendar
      path: month_view/
  cupertino_calendar_date_reminds_view:
    git:
      url: https://github.com/LahaLuhem/cupertino_calendar
      path: date_reminds_view/
flutter: