name: cupertino_calendar_month_view
description: Display date in a month for Cupertino Calendar
version: 1.0.0-beta-1
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.3"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar_structre: ^1.0.0-beta-5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: