name: cupertino_calendar_month_view
description: Display date in a month for Cupertino Calendar with events and holidays supported
version: 1.0.2
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/cupertino_calendar
issue_tracker: https://github.com/rk0cc/cupertino_calendar/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar_structre:
    git:
      url: https://github.com/LahaLuhem/cupertino_calendar
      path: structre/
dev_dependencies:
  flutter_test:
    sdk: flutter