name: cupertino_calendar_month_view_example
description: Demo project of cupertino_calendar_month_view
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar_structre: ^1.0.0-beta-8+1
  cupertino_calendar_month_view:
    path: ../
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
