name: cupertino_calendar_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  flutter: '>=3.10.0 <4.0.0'
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_calendar:
    path: ../
  cupertino_icons: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true