name: Cupertino Calendar Month View test
on:
  push:
    branches:
      - main
    paths:
      - month_view/lib/**.dart
      - month_view/test/**.dart
      - .github/workflows/month_view_test.yml
defaults:
  run:
    working-directory: month_view
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - stable
          - beta
          - dev
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: ${{ matrix.channel }}
      - name: Install depencies
        run: flutter pub get
      - name: Code analyse
        run: flutter analyze --no-fatal-infos
      - name: Run test
        run: flutter test

