name: Cupertino Calendar Structre test
on:
  push:
    branches:
      - main
    paths:
      - structre/lib/**.dart
      - structre/test/**.dart
      - .github/workflows/structre_test.yml
defaults:
  run:
    working-directory: structre
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - stable
          - beta
          - dev
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.channel }}
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
